### ISSUE TITLE
OS X/iTerm 2: abduco requires keyboard input after process ends to quit, pegs a CPU

### ISSUE THREAD

**Issue by tomjakubowski** [martanne/abduco#11]
Running master revision 586d751d7e8d52a14b165b08aaef602bccf998f5:

```
% abduco -v
abduco-0.5 © 2013-2015 Marc André Tanner
```

I create a new abduco session running an ephemeral process:

```
% abduco -c foo sh -c 'echo 'hello world''
```

The terminal goes blank, "hello world" is printed:

<img width="570" alt="screen shot 2016-01-19 at 12 44 54 pm" src="https://cloud.githubusercontent.com/assets/667901/12431477/759c60a6-beaa-11e5-8d32-f152eb4f221b.png">

At this point, abduco is using 99% CPU.  If I press `<RET>` or something, then abduco quits. If I don't, then abduco survives even the closing of its terminal window and I have an annoying spinning process doing nothing but wasting battery life and cycles :-)

**Comment by tomjakubowski** [comment]
If I run:

```
% make debug
% ./abduco -n debug echo 'hello world' 2> server-log
```

The server-log file grows indefinitely at a rate of roughly ~3MB/s.  The log file looks like this

```
read_all(255)
read_all(255)
server-read-pty:: CONTENT hello world

server pty died: 0
server-read-pty:: CONTENT
server-read-pty:: CONTENT
server-read-pty:: CONTENT
server-read-pty:: CONTENT
server-read-pty:: CONTENT
[...]
```

Where `[...]` means the previous line repeats.

**Comment by martanne** [comment]
Thanks for the detailed report! Did the latest commit improve things?

**Comment by tomjakubowski** [comment]
Yes, indeed it did. Thank you for the quick fix!
