### ISSUE TITLE
^4 detaches

### ISSUE THREAD

**Issue by googl** [martanne/abduco#18]
Ctrl-4 works the same as Ctrl-\ on my system. I am uncertain if it is the same with other users. The distribution is NixOS-unstable with US keymap. What more information may I supply?

**Comment by lanodan** [comment]
Also detaches for me on gentoo/Linux using st and us keyboard.

**Comment by josuah** [comment]
Try this in a terminal, without abduco, in the shell directly (bash, mksh, zsh...):  press CTRL + V (insert next character literally) then CTRL + 4.

For me, it indeed inserted `^\`, aka CTRL + \.

So it is normal abduco behave this way, and it is not an issue from abduco, but from the terminal itself.  :)

What I did is using CTRL + z as a detach key, as it often reserved to "put the program in the background", which abduco does quite well ;).

**Comment by martanne** [comment]
Many [terminals map](http://unix.stackexchange.com/a/226333) <kbd>Ctrl+4</kbd> to `^\`.

Closing, because this is not really an abduco issue.
