### ISSUE TITLE
abduco -c foo bash, then mc

### ISSUE THREAD

**Issue by safinaskar** [martanne/abduco#23]
Run abduco -c foo bash, then run mc inside this bash.
The exit from mc.
You will see the terminal restored to state in which it was before running abduco.
This is bad.
It should be restored to state before running mc

**Comment by safinaskar** [comment]
abduco 0.6

**Comment by Tsutsukakushi** [comment]
Seems to happen with any ncurses program. Same happened with `htop`, `ranger` and `mtm` when I just tried it.

**Comment by martanne** [comment]
Can't seem to reproduce right now, but the limitations/hakcs regarding the alternate screen buffer are also related to #32.
