### ISSUE TITLE
Changing the detach key isn't working.

### ISSUE THREAD

**Issue by jcjordyn130** [martanne/abduco#28]
I can't seem to change the detach key to CTRL+[anything other then \\], it just flat out doesn't work, I've tried setting it from config.def.h also but no dice.

**Comment by alexanderjeurissen** [comment]
@jcjordyn130 I can't reproduce this error, for me it works just fine on OSX:

`abduco -e ^z -c neovim nvim`

pressing Ctrl+z in that case detaches the abduco session for my neovim process.

**Comment by martanne** [comment]
I also can't reproduce it, seems to work fine.
