### ISSUE TITLE
$SRC used by CRUX Linux distro's `pkgmk`, causing conflict

### ISSUE THREAD

**Issue by Greduan** [martanne/abduco#3]
Hey, just wanted to let you know that both `abduco`'s and `dvtm`'s Makefiles use the `$SRC` variable.

This variable is used by the `pkgmk` command in [CRUX](https://crux.nu/), so it causes this conflict: http://sprunge.us/NTVK

I fixed by adding the following to the Pkgfile before using `make`:

``` sh
sed -i "s/SRC/SSRC/g" Makefile
```

One of the guys at CRUX already came up with a solution, but discussion ensuing suggests this is an edge case so changes are not necessary and/or not going to be made, the Pkgfile should just work around it.

Just thought you should know though, feel free to close this as soon as you read it. :)

P.S.: Probably should have just sent you an email, but whatever, what's been done is done. :P

**Comment by martanne** [comment]
Could you please test whether 81d934ea fixes the issue?

**Comment by Greduan** [comment]
Sure! Give me a sec...

**Comment by Greduan** [comment]
It works if I build from Git, not entirely sure if that commit is the reason. Let me checkout an older version before compiling...

**Comment by Greduan** [comment]
Yes that does fix it! Awesome! :D 

Thanks man. :)
