### ISSUE TITLE
Set an environment variable with the session name/socket.

### ISSUE THREAD

**Issue by ccrusius** [martanne/abduco#33]
I use `abduco` without `dvtm`, and have on average four to five sessions going. It would be nice if I could see which session I'm currently in at the shell prompt. Currently, the best way I can think of is to hack around with `ps` and `$PPID`, but that is hard to make portable, and has me parsing an `abduco` CLI call.

The suggestion would be for `abduco` to automatically set, for example, an `ABDUCO_SESSION` and/or `ABDUCO_SOCKET` environment variable for each session.

**Comment by martanne** [comment]
Hi, please let me know whether 4c3e2c8c70cf42f15c922a4038bea63c1ab3dfa2 and c33ee37b435bcdabe9022d10a56da97e531bbad3 work as expected?

**Comment by ccrusius** [comment]
Tested and works great, thanks!
