### ISSUE TITLE
Is abdcuo dead code base or in a need of maintainer?

### ISSUE THREAD

**Issue by skrat** [martanne/abduco#36]
I see issues, and PRs, without any response at all, in years.

**Comment by guygma** [comment]
Yeah, this is a good question. Great tool, but not if it isn't maintained.

**Comment by demonking** [comment]
i think, the maintainer martanne is to busy now.
Last commit was in July for his vis editor.

@martanne can you give us a heartbeat?

**Comment by martanne** [comment]
Hi, I'm alive and well.

Eventually I would like to address #32, modernize dvtm and make it work smoothly in combination with abduco to solve most of the remaining issues.

However, time remains limiting factor ...

**Comment by seamusdemora** [comment]
@martanne said:
> However, time remains limiting factor ...

Mmm... your last post here was Feb 15, 2021, ( #46 ) - over 4 years ago. 
Assuming that you're still **alive**, I'd have to say that "time" is not the limiting factor - is it?
