### ISSUE TITLE
Conflict with CMUS

### ISSUE THREAD

**Issue by Henry-Wilson** [martanne/abduco#37]
I love to use Abduco to send my CMUS session away from me, but when I do, I'll encounter a bug upon my return to CMUS. The bug goes like this: the keybindings don't quite work as expected, i.e, the left and right arrows cause deletion of albums from my list if they are pressed enough.

**Comment by zsugabubus** [comment]
I think it's related to #32. Try `abduco -A cmus dvtm cmus`.

**Comment by martanne** [comment]
Yes, this is indeed likely the same issue.
