### ISSUE TITLE
Various keys behaving funky (KEY_HOME, KEY_IC, etc.)

### ISSUE THREAD

**Issue by wart-github** [martanne/abduco#42]
I had originally thought this was a dvtm problem, but I've now narrowed it to some code that is common between dtach and abduco.  See [this issue report](https://github.com/martanne/dvtm/issues/116).  

Basically, if you set MOD to KEY_HOME in dvtm, and then launch one st and execute 'abduco -c test' and then launch a second st and execute 'abduco -a test', KEY_HOME, KEY_IC, KEY_DC, KEY_RIGHT, etc. won't get passed along (or get passed along as distinct key codes) in the second st.

You can reproduce this without dvtm, e.g., abduco -c test yash.

The same behavior occurs in dtach; hence I think it is some code common to dtach and abduco.

**Comment by martanne** [comment]
Thanks for the analysis. The root cause of this is discussed in #32 which references all related issues.
