### ISSUE TITLE
get current session

### ISSUE THREAD

**Issue by basbebe** [martanne/abduco#46]
I'm using FreeBSD 12.2 & macOS 11.2, both w/ fish shell.

I would like to know the current session's name and socket.

I found issue https://github.com/martanne/abduco/issues/33 but I don't have these env variables on either system.

**Comment by martanne** [comment]
Are you sure that you are using the latest version? The [relevant code](https://github.com/martanne/abduco/blob/8c32909a159aaa9484c82b71f05b7a73321eb491/abduco.c#L387-L388) is present in current git HEAD.

**Comment by basbebe** [comment]
According to `man abduco `, both systems have 0.6

I'm sorry, I guess I missed the fact that there hasn't been a release since then.

Is there any plan on when a new release will come out?

FreeBSD ports seem to rely on that…
