### ISSUE TITLE
Session still active after command terminated; connection refused

### ISSUE THREAD

**Issue by jangler** [martanne/abduco#5]
I was ssh'ed into an abduco session created with command "irssi", and irssi (or something in the ssh -> abduco -> irssi chain) stopped responding to input. I killed ssh, and when I reconnected I found that the abduco session was still "active" and displayed with an * in the session list, meaning that a client was considered to be still connected, even though no irssi process was running anymore. Trying to connect to the session resulted in the error message "attach session: Connection refused".

I haven't manually removed the socket yet, just in case there's still some debugging that could be done on it.

**Comment by martanne** [comment]
Sorry for the late answer. Is this reproducible (did it happen more than once)? Why did the irssi (or abduco server process) die? Killing the ssh client should only affect the abduco client process.

I tried it with ping and as far as I can see, it worked as expected:

    $ ssh server
    $ abduco -c foo ping google.com

Then locally, I killed the ssh client and reconnect.

    $ ssh server
    $ abduco
    Active sessions (on host optimus7.inf.ethz.ch)
      Tue    2015-06-23 13:44:48    foo

As expected the session is still alive and no clients are connected i.e. no `*` is displayed in the listing above.

    $ abduco -a foo
    [ ping output omitted]
    ...
    CTRL+C
    abduco: foo: session terminated with exit status 0

**Comment by jangler** [comment]
No, I guess I've only seen it once. Still have that broken session hanging around, though. I'll see if I can figure out a way to reproduce this.

**Comment by martanne** [comment]
> Still have that broken session hanging around, though.

That is the socket still exists? Could you check whether some process still has it opened (using e.g. `lsof` )?

I suspect that the abduco server process was killed with `SIGKILL` (in which case the socket will not be deleted because the signal can not be handled) instead of the default `SIGTERM` signal.

    $ abduco -c sigterm ping google.com
    $ killall abduco
    $ abduco -c sigkill ping google.com
    $ killall -9 abduco
    $ abduco
    Active sessions (on host debbook)
    * Tue    2015-06-23 14:26:23    sigkill

As you can see, the first session was properly cleaned up, however the latter seems analogous to your case.

At the moment I'm not sure how the cleanup procedure could be improved ...

**Comment by jangler** [comment]
Yeah, there's not much to do if you get `SIGKILL`. I checked using `lsof` and no process has the socket open. Any idea *why* abduco might have recieved `SIGKILL`?

**Comment by rychipman** [comment]
I just had this happen to me now. I was running abduco in an ssh session to a vm, and the host machine rebooted. When I started the vm back up, I was stuck with a non-terminated but unattachable abduco session as described above. The socket is still present in the `~/.abduco` directory.

**Comment by martanne** [comment]
Could you check whether the latest commits fix the issue? Such dead sockets should now be ignored. Only lightly tested though.

Adding @rpmohn since I know he is a heavy abduco user.

**Comment by jangler** [comment]
Works for me.

**Comment by rpmohn** [comment]
I haven't seen this, but I will pull the changes and test tomorrow.

**Comment by martanne** [comment]
I think this is fixed.

@rpmohn have you had time to test it in your AIX environment?

In general we have accumulated enough fixes and small improvements to warrant another release. Does current git HEAD work for you guys?

**Comment by jangler** [comment]
Working fine so far. I'll let you know if I have any problems.
